//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Selectors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Selectors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Src.Services.Selectors", typeof(Selectors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.row &gt; div.span8 &gt; ul &gt; li &gt; p &gt; a.
        /// </summary>
        internal static string AllTitlesOnPage {
            get {
                return ResourceManager.GetString("AllTitlesOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;название&quot;)]/../em.
        /// </summary>
        internal static string AnotherTitleNamesX {
            get {
                return ResourceManager.GetString("AnotherTitleNamesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;Автор&quot;)]/../em/a.
        /// </summary>
        internal static string AuthorX {
            get {
                return ResourceManager.GetString("AuthorX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;Средний&apos;)]/following-sibling::dd[1].
        /// </summary>
        internal static string AverageChapterSizeX {
            get {
                return ResourceManager.GetString("AverageChapterSizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;главу&apos;)]/following-sibling::dd[1].
        /// </summary>
        internal static string BaseChapterPriceX {
            get {
                return ResourceManager.GetString("BaseChapterPriceX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbody td input[data-price].
        /// </summary>
        internal static string ChaptersPrice {
            get {
                return ResourceManager.GetString("ChaptersPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #liker &gt; span.
        /// </summary>
        internal static string CountLikes {
            get {
                return ResourceManager.GetString("CountLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5[contains(text(),&quot;Оценки&quot;)]/../dl/div/span/span/span.
        /// </summary>
        internal static string CountPeoplesVoicesX {
            get {
                return ResourceManager.GetString("CountPeoplesVoicesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/div[@class=&apos;btn-toolbar&apos;].
        /// </summary>
        internal static string DescriptionAfterThisX {
            get {
                return ResourceManager.GetString("DescriptionAfterThisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;Жанры&apos;)]/following-sibling::dd[1].
        /// </summary>
        internal static string GenresX {
            get {
                return ResourceManager.GetString("GenresX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#Info &gt; div.images &gt; div.slick &gt; div &gt; img.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;errorpage&apos;]/p[contains(text(), &quot;для лиц старше 18&quot;)].
        /// </summary>
        internal static string IsPageBlokedByAgeX {
            get {
                return ResourceManager.GetString("IsPageBlokedByAgeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5[contains(text(),&quot;Оценки&quot;)]/../dl/div/span[last()].
        /// </summary>
        internal static string KeyPeopleVoicesX {
            get {
                return ResourceManager.GetString("KeyPeopleVoicesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5[contains(text(),&quot;Ссылки&quot;)]/../dd/ul/li/a.
        /// </summary>
        internal static string LinksX {
            get {
                return ResourceManager.GetString("LinksX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /site/proxy?l=.
        /// </summary>
        internal static string ProxyString {
            get {
                return ResourceManager.GetString("ProxyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;Издательство&quot;)]/../em/a.
        /// </summary>
        internal static string PublisherX {
            get {
                return ResourceManager.GetString("PublisherX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;Выпуск&quot;)]/../em.
        /// </summary>
        internal static string PublishStatusX {
            get {
                return ResourceManager.GetString("PublishStatusX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;Год&quot;)]/../em.
        /// </summary>
        internal static string PublishYearX {
            get {
                return ResourceManager.GetString("PublishYearX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;Info&quot;]/table/tbody/tr/td/strong[contains(text(),&quot;Произведение:&quot;)]/../../td[last()]/div/text()[6].
        /// </summary>
        internal static string RateOfTitleX {
            get {
                return ResourceManager.GetString("RateOfTitleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;Info&quot;]/table/tbody/tr/td/strong[contains(text(),&quot;перевода:&quot;)]/../../td[last()]/div/text()[6].
        /// </summary>
        internal static string RateOfTranslateX {
            get {
                return ResourceManager.GetString("RateOfTranslateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;Info&quot;]/table/tbody/tr/td/strong[contains(text(),&quot;озвучки:&quot;)]/../../td[last()]/div/text()[6].
        /// </summary>
        internal static string RateOfVoicesX {
            get {
                return ResourceManager.GetString("RateOfVoicesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;Тэги&apos;)]/following-sibling::dd[1].
        /// </summary>
        internal static string TagsX {
            get {
                return ResourceManager.GetString("TagsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;Группа&quot;)]/../em/a.
        /// </summary>
        internal static string TeamX {
            get {
                return ResourceManager.GetString("TeamX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;Info&apos;]/p/strong[contains(text(),&quot;18+&quot;)].
        /// </summary>
        internal static string TitleIsFor18X {
            get {
                return ResourceManager.GetString("TitleIsFor18X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.span8 &gt; h1.
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.row &gt; div.span8 &gt; ul &gt; li.active &gt; a.
        /// </summary>
        internal static string TitleUrl {
            get {
                return ResourceManager.GetString("TitleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;Размер&apos;)]/following-sibling::dd[1].
        /// </summary>
        internal static string TranslateSizeX {
            get {
                return ResourceManager.GetString("TranslateSizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;tools&apos;]/h5/../dl/dt[contains(text(), &apos;Состояние&apos;)]/following-sibling::dd[1]/span.
        /// </summary>
        internal static string TranslateStatusX {
            get {
                return ResourceManager.GetString("TranslateStatusX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Info &gt; p.cat.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
